name = "vetapp-frontend"
main = "worker.ts"
compatibility_date = "2024-10-01"

assets = { directory = "dist", binding = "ASSETS" }

[vars]
PROJECT_NAME = "vetapp_frontend"
VITE_APP_NETWORK = "testnet"
VITE_MODULE_TAPP_ACCOUNT_ADDRESS = "0x6234763d11bd84dfbcadb6f13cdde608c03a88deecd6c2c3106188c174ae53db"
VITE_MODULE_VETAPP_ACCOUNT_ADDRESS = "0x4d3cb18dfe52ed363351cd04875bd9661ee82db05b4cc6cf1f450f6bb37d1b1c"
VITE_MODULE_GAUGE_ACCOUNT_ADDRESS = "0x271ce40865ecb0a1a5f82da25e616bd209be24df3a8434af95e8f891fe4867ed"
