name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0x91b6790413187d46fb40a1714ddd593bdfd61a9a082eb72fefc746f9f72836c2"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0x6da5b58a9e72b04fddf766c89fd1188233d482c266fa390600a656d30bf2e320"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0xdb94fef29f2340da176dd463474a8042564d72c270c97b77f203257641b1df49"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0x23346ca5d4f85471bb499a65a36e072e31d82bae204129f49fe0e2bbd861c692"
tapp="0x509242f515271faa79ce3eddac6e3106ada95c85e6eaadb83c5876463436281b"
ve_tapp="0xb60174fa7d3fb35721c1e6abcc3c9ca79239f3297ca8bb279accf139fdd5f70f"
ve_tapp_lib="0xdb1c6ffcbd45609701d72064aacfde45cf54d0dba61408ef73d5825baec99896"
