name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0x6dd7b923b6aa3698dd467c3fe4f5a69f812ac4e85fc1021a974231770da5269f"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0xc27be0a13e2b04f2dec74ad5b5348fdfafd73ef948ac778295c029a0b07c380e"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0xbb3b0d42746795f0935a5264b00273a96be6233b582769f02edadfaec4402bc0"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0x8dfe59d7392604bed92c2ff0480b2c926a7ce959c10990f539f30f3838bbf89b"
tapp="0x50316aa1da4e3410c19c99bb7149c312e90a9142aada0cfce1bde1d9af22021d"
ve_tapp="0x107eb03e509ead04501d03229ac5fae332c73826aac932f84d44adff1b1106ad"
ve_tapp_lib="0x49f724b3c026b9e84ae83b4e7a1ce3cf780da35b4b281cca106f034dc6afd941"
views="0xa484d133d3e25fb752b88016e3b18720c332e883a09ce6d71147b55c9dacb9da"
sor="0x6fd4409824a7186cb2d2735703ede61b4008cd2b2b3b1ad9efa66eb7072d8226"
