name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0x6dd7b923b6aa3698dd467c3fe4f5a69f812ac4e85fc1021a974231770da5269f"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0xc27be0a13e2b04f2dec74ad5b5348fdfafd73ef948ac778295c029a0b07c380e"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0x65d3917fc4a12d9abda89ac154c59a9fa211dcc1cd03d3a9737bf3030e8cd880"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0x8dfe59d7392604bed92c2ff0480b2c926a7ce959c10990f539f30f3838bbf89b"
tapp="0x7009744e6e65f714a72a8b083d5fcaf96651053bfc600d8fa171b05d55866d0b"
ve_tapp="0xeb2ccd97540eef2ef4541b43857745f7644f85b4fbdb8850d7113c6938deb1a3"
ve_tapp_lib="0xed3daa66287ceaedacdd09f381ec94e2c83e03fb977f229528e0ec204b430d07"
views="0xa484d133d3e25fb752b88016e3b18720c332e883a09ce6d71147b55c9dacb9da"
sor="0x6fd4409824a7186cb2d2735703ede61b4008cd2b2b3b1ad9efa66eb7072d8226"
ve_tapp_helper="0xccc4ea90b37cd55b76c7c430377bc82c72d9b3e0aaf749a9ce2d398062ed76c1"
