name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "mainnet"
VITE_APTOS_API_KEY="AG-7OZ31OVYC9DD7JWOVP8VK3NFXDQUERHGX"

amm="0x0b01a9ecc89b51481d92c3a4ff831e7864eceaa6c609a3691e0e8c0a050eeab7"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0x5c2e5a4d1b355b939ab160c618ed5504a6e1addf109388aa3b83b73b207ab6c7"
escrow="0x1bd6f1f2096d4a3151443cc0a7cd36f071445c8edb335cb99fa8a413a47c9e8b"
gauge="0x296a63c4074a1e7475e394db6a5b099755481f9c16d2c19237f82cc80d0e2486"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0xa611a8ba7261ed1f4d3afe4ac2166fc9f3180103e3296772d593a1e2720c7405"
tapp="0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a"
ve_tapp="0x8a5ef085f2a8eb714c1462392d52371dfef0f97325d140b605e8306fafcf398b"
ve_tapp_lib="0xa9e15e4f04676f8bc087568b81aae0ef01f9b890aea599f574c1630cece891fe"
views="0xf5840b576a3a6a42464814bc32ae1160c50456fb885c62be389b817e75b2a385"
sor="0x7bd64a730c360a87da24187d6d2e9128310ff25419facb3000d6b2293a06280a"
ve_tapp_helper="0xf5a2d90035563252eea6904b24efca092c520e183c42515d21534da0fe345af1"