name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0x4094236fc554f4f3f56bff0b69ce6f3f842147ccad1a95ecfc344150ca0c3073"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0x07fde5b12ff800b4f241fbd934e7bd987beea734cf97f582e97a3a88cf04f07b"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0x1f3040ea5da2c0bd1e94cea8e1b90957b8c4e792568d72178ba0f1444e153509"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0xef1f0588a2d8f10f0299999b77ec18e3eddeb7b85549c35a0bc2995d560321a0"
tapp="0x44f202b14a84cba8bb973e2c62b2cb7879f34dd2101137428e83dee2d7692d51"
ve_tapp="0x456f3d13a66465b004aaa74e805363ca397c315f565551bdd6090f7d747c00ba"
ve_tapp_lib="0xc6aa78e1c1aa878e7b6441d1d25f5b36dcc4de9e455b436b6e32823141801655"
views="0x7aaeb01d485df98e16d355bfeca60417523062b3448af7641b873f6e26f4f4f1"
sor="0x25e626649f00623e8a95809a2213a653da8b74cc09cb7251cb2697fcbcb9c52c"
ve_tapp_helper="0x4aa00a746b2c2e98789786c012ad59251471bad0b7c04583af6303ee6d8e5951"
