name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *",
  "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"
VITE_MODULE_TAPP_ACCOUNT_ADDRESS = "0x3337b00b38f91a2f54dd4cb6fb2fda21521ad8b1ce1c3b925dfff4e6ca42242d"
VITE_MODULE_VETAPP_ACCOUNT_ADDRESS = "0x5bb6906706218809af1539361660de2d8a4b97c843baf64f60c3930d209f88a7"
VITE_MODULE_VETAPP_LIB_ACCOUNT_ADDRESS = "0xdb1c6ffcbd45609701d72064aacfde45cf54d0dba61408ef73d5825baec99896"
VITE_MODULE_GAUGE_ACCOUNT_ADDRESS = "0x2921acfbadd890750864d4784ca3eb08a2a9026dee2f96ed9214b9bd1f0c59c9"
VITE_MODULE_ESCROW_ACCOUNT_ADDRESS = "0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
VITE_MODULE_BONDING_CURVE_ACCOUNT_ADDRESS = "0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
VITE_MODULE_NFT_SPRINGBOARD_ACCOUNT_ADDRESS = "0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
VITE_MODULE_AMM_ACCOUNT_ADDRESS = "0x91b6790413187d46fb40a1714ddd593bdfd61a9a082eb72fefc746f9f72836c2"
VITE_MODULE_CLMM_ACCOUNT_ADDRESS = "0xdf9bcf5bf720cc6d32862b18fc4b222b284158b553d6c59382ffef102f94d73b"
VITE_MODULE_STABLE_ACCOUNT_ADDRESS = "0x23346ca5d4f85471bb499a65a36e072e31d82bae204129f49fe0e2bbd861c692"
