name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = ["1 * * * *"]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
