name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0xf4ca29658de9f34480a6b35a3a64e91320e45747e023525aa8c7d31d4fdf1566"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0x08c25945c927dbd80cfbbd5e3692c67c77f2ac783cb6b7bf68d723a5cbf1ba62"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0xf9ab976e24945f228b675211abc26dad37240f58995eebc9ed886d2b5585d89e"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0xf3b5dc05f0ba56ced30c72f587da2a0810043612eee2e45394c11f49cf1cd341"
tapp="0xc5cb1d1648c7e373d64769472bd5264152959b7364d02d587bbfe039dd572c9a"
ve_tapp="0xa779e7090ac1a1c5ea8a5eee7396bfa3a4193550eaa83db2875c33c4745a18ac"
ve_tapp_lib="0xd04f5ca7db3d5df8a24aa45f1f08d6bac13d96ccd5c6b7537cbe4896254495ba"
views="0xb4bb4aecaee8e6ca46d6e15984c1090370d5b1a15f279c00d0153c8b5a20f005"
sor="0x5dabed6f2ca374c88f1204d04875730d90b376afbe44c7b23864c81e2e0c3c9b"
ve_tapp_helper="0xdf2a91f95943dca50bfc6e0a763e9857492f9eb966749774dd606c8a85b26580"
